### ISSUE TITLE
Please provide mod dll

### ISSUE THREAD

**Issue by deinlandel** [chrislee0419/hellosFilters#1]
Hello! I understand that this is a Work in progress but filter by note density is crucial for me. Could you provide mod DLL in releases please?

**Comment by chrislee0419** [comment]
For now, I'm not going to put up the DLLs for all the mods in the release pages, but I can at least provide a zip of them here: [Plugins.zip](https://github.com/chrislee0419/hellosFilters/files/6738291/Plugins.zip)

Keep in mind that the [required base mod](https://github.com/chrislee0419/hellosUI) is currently incompatible with SongBrowser, so you will need to disable that if you are going to use these mods. You can do that by opening the `Beat Saber/UserData/Disabled Mods.json` file and adding the id "SongBrowser" into the "DisabledModIds" array.

Also, I've included my [search mod](https://github.com/chrislee0419/hellosSearch), in case you need something to search songs with after disabling SongBrowser.

**Comment by deinlandel** [comment]
Thanks a lot!
